### ISSUE TITLE
[0.5pt] Add header - group task

### ISSUE THREAD

**Issue by imranhossainemi** [byiringiroscar/movies-final-capstone-microverse-javascript#17]
Create page header according to the wireframe:

<img width="541" alt="Screenshot 2021-06-27 at 21 42 24" src="https://user-images.githubusercontent.com/7466903/123557332-ac3eee80-d790-11eb-91c8-9f8a6a38a4ff.png">

**Comment by AbayomiOlaoye** [comment]
- Great work @Team :clap: 
- [ ] However, to facilitate your work in an efficient manner, I believe that is important that you assign tasks so that each member knows exactly what and when activities are expected. This will reduce the chance of conflicts or forgetfulness as to who does what.
_Kindly assign the tasks to all members to issues with `group task` clause or individually where you have alphabets :wink: _
