### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by imranhossainemi** [byiringiroscar/movies-final-capstone-microverse-javascript#19]
Choose images, text, icons, fonts.

**Comment by AbayomiOlaoye** [comment]
- Great work @Team :clap: 
- [ ] However, to facilitate your work in an efficient manner, I believe that is important that you assign tasks so that each member knows exactly what and when activities are expected. This will reduce the chance of conflicts or forgetfulness as to who does what.
_Kindly assign the tasks to all members to issues with `group task` clause or individually where you have alphabets :wink:_
